// <auto-generated />
namespace Midterm_Demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StudentData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentData));
        
        string IMigrationMetadata.Id
        {
            get { return "202012050307327_StudentData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
